### ISSUE TITLE
pascalio breaks class properties convention

### ISSUE THREAD

**Issue by antispam88** [SAmeis/pascalio#6] opened 2018-12-30 20:31 UTC
Hi,

you wrote to comment your package on http://www.lazarusforum.de, but there still exists the issue regarding registration (http://www.lazarusforum.de/viewtopic.php?f=14&t=11832).

So I have to make my comment hear:
Your code breaks the class properties convention (https://www.freepascal.org/docs-html/3.0.0/ref/refse39.html). In FPC 3.0.4 your code is wrongly accepted, but in all version 3.1+ it isn't allowed anymore (see http://forum.lazarus-ide.org/index.php/topic,42265.msg306140.html#msg306140).

Best regards,
antispam88

**Comment by SAmeis** [comment] 2019-01-08 16:14
The issue is fixed with commit 231cff0d272e134c224353c2f7de481ab4cfa9fc. This converts most class properties to simple instance properties because I didn't find an solution for having this information in class properties while defining the actual values in descendent classes.

**Closed by SAmeis** 2019-01-08 16:14 UTC
